Repository kthchew/CatCorp, pull requests merged in 2024-04, with the labels that each got.

#50 updated all existing buttons
  Frontend/src/Home.jsx
  Frontend/src/css/App.css
  Frontend/src/img/UI/assignment.png
  Frontend/src/img/UI/reward.png
  Frontend/src/img/UI/store_button.png
Labels: enhancement, good first issue

#47 Add cat gain/lose notifications
  Backend/cat.js
  Backend/generic-food.js
  Backend/user.js
  Frontend/src/App.jsx
  Frontend/src/CatGainNotification.jsx
  Frontend/src/CatLoseNotification.jsx
  Frontend/src/Checklist.jsx
  Frontend/src/Home.jsx
  Frontend/src/Rewards.jsx
  Frontend/src/Store.jsx
  Frontend/src/css/CatChangeNotification.css
Labels: enhancement

#49 Added Cat Selection Functionality
  Frontend/src/Cat.jsx
  Frontend/src/CatView.jsx
  Frontend/src/Home.jsx
  Frontend/src/css/Cat.css
Labels: enhancement

#51 API box and font change
  Frontend/src/Login.jsx
  Frontend/src/css/Login.css
Labels: enhancement, good first issue

#57 Added Streak Functionality
  Backend/generic-food.js
  Backend/user.js
  Frontend/src/Home.jsx
  Frontend/src/Rewards.jsx
  Frontend/src/css/Rewards.css
Labels: enhancement

#55 Boss screen
  Backend/generic-food.js
  Backend/server.js
  Backend/user.js
  Frontend/src/App.jsx
  Frontend/src/Bosses.jsx
  Frontend/src/Checklist.jsx
  Frontend/src/Home.jsx
  Frontend/src/Leaderboard.jsx
  Frontend/src/Login.jsx
  Frontend/src/Rewards.jsx
  Frontend/src/css/App.css
  Frontend/src/css/Login.css
  Frontend/src/css/Rewards.css
  Frontend/src/img/UI/boss_fight.png
  Frontend/src/img/bossTemp.png
Labels: enhancement, good first issue

#68 oops
  Frontend/src/Login.jsx
Labels: good first issue
